<?php

declare(strict_types=1);

/** @return array<string, string> Map of book title => story science topic label */
function story_topics_by_title(): array
{
    return [
        'The Stem That Carried a River' => 'Xylem & water transport',
        'The Mystery of the Sunny Stone' => 'Warm-blooded vs. Cold-blooded animals',
        "The Ship That Wouldn't Sink" => 'Buoyancy & density',
        "The Body's Tiny Defense System" => 'Immune system',
        'The Sky That Started Spinning' => 'Tornadoes',
        'The Planetary Adventure' => 'Solar System',
        'The Day the Sun Disappeared' => 'Eclipses',
        'The Town That Forgot the Stars' => 'Light pollution & constellations',
        'The Plants That Ate Lunch' => 'Carnivorous plants',
        'The Plants That Saved Every Drop' => 'Plant adaptations for water conservation',
        'The Trees That Let Go' => 'Deciduous trees',
        'The Forest That Stayed Green' => 'Evergreen trees',
        'The Web in the Meadow' => 'Food chains & Food webs',
        'The Flower That Sent a Message' => 'Pollination',
        'The Plant With Many Jobs' => 'Plant parts & functions',
        'The Tree That Made Its Own Lunch' => 'Photosynthesis',
        'The Seed That Slept Underground' => 'Germination',
        'The Scaly Trail' => 'Reptiles',
        'The Six Leg Secret' => 'Insects',
        'The Hidden Color Clue' => 'Camouflage',
        'The Feather Trail' => 'Birds',
        'The Cozy Cave Clue' => 'Hibernation',
        'The Butterfly Garden Clue' => 'Butterfly life cycle (metamorphosis)',
        'The Pond Puzzle' => 'Frog life cycle',
        'The Backbone Clue' => 'Vertebrates vs. invertebrates',
        'The Mystery of Day and Night Animals' => 'Nocturnal vs. diurnal animals',
        'The Energy That Made Everything Happen' => 'Forms of energy & energy transformation',
        'The Backpack That Felt Lighter' => 'Mass vs. Weight',
        'The Heat That Traveled Three Ways' => 'Conduction, convection & radiation',
        'The Mystery of Heat and Temperature' => 'Heat vs. Temperature',
        'The Mystery of the Heavy Little Cube' => 'Density',
        'The Air that Loved to Climb' => 'Why warm air rises and cool air sinks',
        'The Wind That Came and Went' => 'Sea Breeze and Land Breeze',
        'The Forest Mystery' => 'Producers, Consumers, and Decomposers',
        'The Forest Team' => 'Biotic & Abiotic Factors',
        'The Green Lake Mystery' => 'Algae & Algal Blooms',
        'The Secret Beneath the Roots' => 'Nitrogen fixation',
        "The River That Couldn't Smile" => 'Plastic pollution',
        'The Mystery of the Missing Sandwich' => 'Bacteria',
        'The Treasure That Never Runs Out' => 'Natural Resources (Renewable & Non-renewable)',
        'The Race Around the Park: Speed and Velocity' => 'Speed & Velocity',
        "The Water That Wouldn't Stay Still" => 'Evaporation vs. Boiling',
        'The Day Water Changed Its Mind' => 'States of matter',
        'The Matter Mystery' => 'What is Matter?',
        'The Dancing Lights in the Sky' => 'Aurora Borealis (Northern Lights)',
        'The Mountain That Rumbled' => 'Volcanoes',
        'The Earth with Hidden Layers' => "Earth's layers",
        'The Raindrop That Took a Trip' => 'Water cycle',
        'The Creatures of the Midnight Sea' => 'Deep-sea ecosystem',
        'The Cloud That Came Down' => 'Fog vs. Mist',
        'The Beach That Ate the Footprints' => 'Tides',
        'Good Bacteria Club' => 'Good bacteria (Microbiome)',
        'The Food Tunnel Adventure' => 'Digestive system',
        'The River Inside You' => 'Circulatory system',
        'The Message Highway Inside You' => 'Nervous system',
        'The Breath That Took a Journey' => 'Respiratory system',
        "The Body's Hidden Frame" => 'Skeletal system',
        'The Control Room Inside Your Head' => 'Brain & nervous system',
        'The Message in the Blood Drop' => 'How blood travels (Blood circulation)',
    ];
}
